### ISSUE TITLE
Simple Calendar/FX Master are required after all

### ISSUE THREAD

**Issue by git-steve-git** [paulcheeba/weather-reports#6]
In the readme, it describes Simple Calendar and FX Master as "recommended to enable all weather report features."

In actual fact, following the setup instructions in the readme, if I try to run the Weather Reports macros _without_ Simple Calendar installed, it doesn't work.  All I get after choosing a region and a season is an error in the console:

Uncaught (in promise) ReferenceError: SimpleCalendar is not defined
    at Macro.eval (eval at _executeScript (foundry.js:20080:16), <anonymous>:43:19)
﻿
To be clear, I'm not opposed to using Simple Calendar myself, but it should be listed as a dependency if the macros won't work without it.

Likewise, the FX Master macros fail without FX Master installed (unsurprisingly.)

Uncaught (in promise) ReferenceError: FXMASTER is not defined
    at Macro.eval (eval at _executeScript (foundry.js:20080:16), <anonymous>:5:1)
    at Macro._executeScript (foundry.js:20082:17)
    at Macro.execute (foundry.js:20037:21)
    at Macro._onClickDocumentLink (foundry.js:20092:17)
    at HTMLAnchorElement._onClickContentLink (foundry.js:57559:17)
﻿
**Suggested Fix**
- Either make Simple Calendar a dependency, or re-work the weather generation macros so they still produce output without it (perhaps with limited functionality) if it's not there.
- Hide the part of the chat output that mentions FX Master, if FX Master is not installed.

**Comment by paulcheeba** [comment]
Ok, this is good to know, I expected it would throw errors if the modules aren't installed, I didn't expect that not having simple calendar installed would cause a critical failure.

I'll modify it so they are dependencies for now.  When I start the next update with 5e automation, I will add an option to enable the Simple Calendar and FXMaster features so the same macros can be used with or without the additional modules.

Thanks for bringing this to my attention.

**Comment by sorrythatuserbla** [comment]
Try to use some `if (game.modules.get("simple-calendar")?.active) { ... }` clauses in the macro.

**Comment by paulcheeba** [comment]
> Try to use some `if (game.modules.get("simple-calendar")?.active) { ... }` clauses in the macro.

Definitely plan to do this for the next big update, for now I'll label it as a dependency.

**Comment by paulcheeba** [comment]
Simple Calendar has been added as a dependency.
