### ISSUE TITLE
Several broken links (see screenshots)

### ISSUE THREAD

**Issue by sorrythatuserbla** [paulcheeba/weather-reports#8]
On startup in the readme:
![grafik](https://user-images.githubusercontent.com/78597675/227955655-7acf4c85-c027-44bc-83b2-a7947de90bfb.png)

Freshly installed and clicked a few times:
![grafik](https://user-images.githubusercontent.com/78597675/227955424-6548aba4-379f-4d1c-a5b8-d656dc49d564.png)

**Comment by paulcheeba** [comment]
I had a feeling those images wouldn't be saved within the document. I'll fix this up this week, thanks for.pointing it out. I will redo the readme.

Regarding the broken links, I'll check those too, I think there may have been a couple that squeezed through my testing as the majority of testing was done in the world and server that contains all the work in progress files, and the link wouldn't have looked broken. This I will also address this week.

Thanks.

**Comment by paulcheeba** [comment]
This has all been fixed, thanks again for pointing the broken links out.
